/*CONNECT TO DATA SOURCE WITH LIBREF AND SUBMIT SAS PROCEDURE*/
LIBNAME TEST_XLS ODBC DATASRC=odbc_excel;

PROC FREQ DATA=TEST_XLS.'Sheet1$'n;
	TABLES CAT;
RUN;

PROC FREQ DATA=TEST.'Sheet2$'n;
	TABLES CAT;
RUN;

/*EXPLICIT PASSTHROUGH WITH CONNECTION VIA ODBC*/
PROC SQL;
	CONNECT TO ODBC AS EXAMPLE (DATASRC=odbc_excel);
		SELECT * FROM CONNECTION TO EXAMPLE
			(SELECT CAT, COUNT(*) AS FREQUENCY
			FROM "Sheet1$"
			GROUP BY CAT);
	DISCONNECT FROM EXAMPLE;
QUIT;

PROC SQL;
	CONNECT TO ODBC AS EXAMPLE (DATASRC=odbc_excel);
		SELECT * FROM CONNECTION TO EXAMPLE
			(SELECT CAT, COUNT(*) AS FREQUENCY
			FROM "Sheet2$"
			GROUP BY CAT);
	DISCONNECT FROM EXAMPLE;
QUIT;
